[display]
ascii = "stack"
seperator = ": "
modules = ["os", "desktop", "shell", "uptime"]
key_lowercase = false # true: "os", false: "OS"
value_lowercase = false # true: "debian", false: "Debian"

[colours]
primary = "\u001B[39m" # reset
accent = "\u001B[36m" # cyan
